// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery'], function(app, $) {
    app.animation('slide-up', [
      '$rootScope', function($rootScope) {
        var animation;
        return animation = {
          setup: function(element) {},
          start: function(element, done) {
            return element.slideUp('normal', function() {
              return done();
            });
          }
        };
      }
    ]);
    return app.animation('slide-down', [
      '$rootScope', function($rootScope) {
        var animation;
        return animation = {
          setup: function(element) {
            return element.css({
              display: 'none'
            });
          },
          start: function(element, done, memo) {
            return element.slideDown('normal', function() {
              return done();
            });
          }
        };
      }
    ]);
  });

}).call(this);
