// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery'], function(app, $) {
    app.animation('fade-out', [
      '$rootScope', function($rootScope) {
        var animation;
        return animation = {
          setup: function(element) {},
          start: function(element, done) {
            element.removeClass('fadeIn');
            element.show().addClass('animated fadeOut');
            return done();
          }
        };
      }
    ]);
    return app.animation('fade-in', [
      '$rootScope', function($rootScope) {
        var animation;
        return animation = {
          setup: function(element) {
            return element.css({
              display: 'none'
            });
          },
          start: function(element, done, memo) {
            element.removeClass('fadeOut');
            element.show().addClass('animated fadeIn');
            return done();
          }
        };
      }
    ]);
  });

}).call(this);
