// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore'], function(_) {
    return function(searchLikeColumns, sortByColumns, oSettings) {
      var aaSorting, filter, order, query, sSearch, sSearchArr, sortArr, sortKeyName, val, word, _i, _j, _k, _len, _len1, _len2;
      if (oSettings == null) {
        oSettings = false;
      }
      query = {};
      sSearch = '';
      if (oSettings) {
        if (oSettings && oSettings.oPreviousSearch && oSettings.oPreviousSearch.sSearch) {
          sSearch = oSettings.oPreviousSearch.sSearch;
        }
        query.offset = oSettings._iDisplayStart;
        query.limit = oSettings._iDisplayLength;
      }
      query.filter = [];
      query.order = [];
      if (sSearch.length > 0) {
        filter = [];
        sSearchArr = sSearch.split(' ');
        for (_i = 0, _len = sSearchArr.length; _i < _len; _i++) {
          word = sSearchArr[_i];
          for (_j = 0, _len1 = searchLikeColumns.length; _j < _len1; _j++) {
            val = searchLikeColumns[_j];
            filter.push([val, 'like', word]);
          }
        }
        query.filter = filter;
      }
      if (oSettings) {
        order = [];
        aaSorting = oSettings.aaSorting;
        if (_.isArray(aaSorting)) {
          for (_k = 0, _len2 = aaSorting.length; _k < _len2; _k++) {
            sortArr = aaSorting[_k];
            sortKeyName = '';
            if (!_.isUndefined(sortByColumns[sortArr[0]])) {
              sortKeyName = sortByColumns[sortArr[0]];
            } else {
              continue;
            }
            /*
            if sortArr[0] is 0
              sortKeyName = 'firstName'
            else if sortArr[0] is 1
              sortKeyName = 'lastName'
            else if sortArr[0] is 2
              sortKeyName = 'email'
            else if sortArr[0] is 3
              sortKeyName = 'phone'
            else
              continue
            */

            order.push([sortKeyName, sortArr[1]]);
          }
          query.order = order;
        }
      }
      return query;
    };
  });

}).call(this);
