// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return function() {
      var TZ, now;
      now = new Date().toString();
      TZ = now.indexOf('(') > -1 ? now.match(/\([^\)]+\)/)[0].match(/[A-Z]/g).join('') : now.match(/[A-Z]{3,4}/)[0];
      if (TZ === 'GMT' && /(GMT\W*\d{4})/.test(now)) {
        TZ = RegExp.$1;
      }
      return TZ;
    };
  });

}).call(this);
