// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'text!views/widgetBreadCrumbs/viewWidgetBreadCrumbs.html', 'text!views/widgetBreadCrumbs/viewNoBreadCrumbs.html'], function(app, viewWidgetBreadCrumbs, viewNoBreadCrumbs) {
    app.run([
      '$templateCache', function($templateCache) {
        $templateCache.put('viewWidgetBreadCrumbs', viewWidgetBreadCrumbs);
        return $templateCache.put('viewNoBreadCrumbs', viewNoBreadCrumbs);
      }
    ]);
    return app.controller('ControllerWidgetBreadCrumbs', [
      '$scope', '$templateCache', 'socket', function($scope, $templateCache, socket) {
        $scope.title = 'Themis';
        return $scope.subtitle = 'by Cobar Systems LLC';
      }
    ]);
  });

}).call(this);
