// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'text!views/viewsDirectives/viewDirectiveInlineEdit.html'], function(app, $, viewDirectiveInlineEdit) {
    return app.directive('inlineEdit', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          template: viewDirectiveInlineEdit,
          scope: {
            model: '='
          },
          link: function(scope, elm, attrs) {
            return elm.bind('keypress', function(e) {
              if (e.charCode === 13) {
                return scope.$apply(function() {
                  return scope.editMode = false;
                });
              }
            });
          }
        };
      }
    ]);
  });

}).call(this);
