// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'text!views/viewsDirectives/viewCollapseWidget.html'], function(app, $, viewCollapseWidget) {
    return app.directive('collapseWidget', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          transclude: true,
          template: viewCollapseWidget,
          scope: {
            title: '@title',
            widgetThemis: '@widgetThemis',
            color: '@color',
            model: '='
          },
          compile: function(element, attrs, transclusionFunc) {
            return function(scope, iterStartElement, attrs) {
              var content, origElem;
              console.log('cw link f');
              scope.collapsed = false;
              scope.toggle = function() {
                return scope.collapsed = !scope.collapsed;
              };
              origElem = transclusionFunc(scope);
              content = origElem.text();
              scope.orig = content;
              return scope.obj = content;
            };
          }
        };
      }
    ]);
  });

}).call(this);
