// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui', 'jqueryFileUpload'], function(app, $, jqueryUi, jqueryFileUpload) {
    return app.directive('fileUpload', [
      '$parse', function($parse) {
        var directive;
        return directive = {
          restrict: 'A',
          scope: {
            filename: '=ngModel',
            done: '=done',
            start: '=start',
            url: '@url'
          },
          link: function(scope, elm, attrs) {
            var doneCallback, startCallback;
            doneCallback = $parse(attrs.done);
            startCallback = $parse(attrs.start);
            return $(elm).fileupload({
              url: attrs.url,
              dataType: 'json',
              paramName: 'files[]',
              success_action_status: 200,
              error: function() {
                console.log('error');
                return console.log(arguments);
              },
              start: function(e, status) {
                return scope.$apply(function() {
                  return scope.start(e, status);
                });
              },
              complete: function(e, status) {
                return scope.$apply(function() {
                  return scope.done(e, status);
                });
              },
              progressall: function(e, data) {
                var progress;
                progress = parseInt(data.loaded / data.total * 100, 10);
                return scope.$apply(function() {
                  return scope.progress = progress;
                });
              },
              done: function(e, data) {
                return console.log('done');
              }
            });
          }
        };
      }
    ]);
  });

}).call(this);
