// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui'], function(app, $, $ui) {
    return app.directive("jqueryAutoComplete", [
      '$compile', function($compile) {
        var directive;
        return directive = {
          restrict: 'A',
          scope: 'isolate',
          link: function(scope, element, attrs) {
            return element.autocomplete({
              source: function(request, response) {
                return response([
                  {
                    name: 'foo'
                  }, {
                    name: 'foo2'
                  }
                ]);
              },
              minLength: 2,
              focus: function() {
                return false;
              },
              select: function(event, ui) {
                this.value = ui.item.name;
                return false;
              }
            }).data('ui-autocomplete')._renderItem = function(ul, item) {
              console.log(ul);
              console.log(item);
              return $('<li>').html('<a>food</a>').appendTo(ul);
            };
          }
        };
      }
    ]);
  });

}).call(this);
