// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui', 'underscore'], function(app, $, jqueryUi, _) {
    return app.directive('slider', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          template: '<div class="slider"></div>',
          scope: {
            options: '=options',
            color: '@color'
          },
          link: function($scope, element, attrs) {
            var sliderElem;
            sliderElem = element.find('.slider');
            sliderElem.addClass('bg-' + $scope.color);
            sliderElem.slider($scope.options);
            return sliderElem.on('slidechange', function(event, ui) {
              return $scope.$apply(function() {
                if (!_.isUndefined($scope.options.value)) {
                  return $scope.options.value = ui.value;
                }
              });
            });
          }
        };
      }
    ]);
  });

}).call(this);
