// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui', 'underscore', 'text!views/widgetEmployeeManager/viewPartialEmployeeManagerEditEmployeeEJS.html'], function(app, $, jqueryUi, _, viewPartialEmployeeManagerEditEmployeeEJS) {
    return app.directive('editEmployee', [
      'apiRequest', function(apiRequest) {
        var directive;
        return directive = {
          restrict: 'A',
          template: viewPartialEmployeeManagerEditEmployeeEJS,
          scope: {
            employeeUid: '@employeeUid',
            resourcePool: '=resourcePool',
            clientOrmShare: '=clientOrmShare'
          },
          link: function($scope, element, attrs) {
            $scope.subViewModel = {};
            $scope.editEmployee = $scope.resourcePool[$scope.employeeUid];
            $scope.subViewModel.editEmployeeForm = _.extend({}, $scope.editEmployee);
            $scope.$watch('subViewModel', function() {
              if (_.isUndefined($scope.dataIsSynced)) {
                $scope.dataIsSynced = true;
              } else {
                $scope.dataIsSynced = false;
              }
              console.log('$scope.dataIsSynced');
              return console.log($scope.dataIsSynced);
            }, true);
            return $scope.subViewModel.updateEmployee = function() {
              $scope.updateInProgress = true;
              return apiRequest.put('employee', $scope.editEmployee.uid, {
                firstName: $scope.subViewModel.editEmployeeForm.firstName,
                lastName: $scope.subViewModel.editEmployeeForm.lastName,
                email: $scope.subViewModel.editEmployeeForm.email,
                phone: $scope.subViewModel.editEmployeeForm.phone
              }, function(response) {
                $scope.dataIsSynced = true;
                $scope.updateInProgress = false;
                return $scope.updateActionComplete = true;
              });
            };
          }
        };
      }
    ]);
  });

}).call(this);
