// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'bootstrap-toggle-buttons'], function(app, $, bootstrapToggleButtons) {
    return app.directive('toggleButton', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          template: '<div><input type="checkbox" ></div>',
          scope: {
            title: '@valueLink'
          },
          replace: true,
          link: function(scope, iterStartElement, attrs) {
            iterStartElement.addClass('toggle');
            return iterStartElement.toggleButtons();
          }
        };
      }
    ]);
  });

}).call(this);
