// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'angular-ui', 'angular-bootstrap'], function(angular) {
    return angular.module('app', ['ui', 'ui.bootstrap']);
  });

}).call(this);
