// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'underscore', 'moment'], function(app, _, moment) {
    return app.filter('fromNow', [
      function() {
        return function(dateString) {
          if (!dateString) {
            return '';
          }
          return moment(new Date(dateString)).fromNow();
        };
      }
    ]);
  });

}).call(this);
