// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'underscore'], function(app, _) {
    return app.filter('toArray', [
      function() {
        return function(obj) {
          var result;
          if (!(obj instanceof Object)) {
            return obj;
          }
          result = _.map(obj, function(val, key) {
            return Object.defineProperty(val, '$key', {
              __proto__: null,
              value: key
            });
          });
          return result;
        };
      }
    ]);
  });

}).call(this);
