// Generated by CoffeeScript 1.6.3
(function() {
  define(['app'], function(app) {
    return app.factory('authenticate', [
      '$rootScope', 'socket', 'apiRequest', function($rootScope, socket, apiRequest) {
        var factory;
        return factory = {
          authenticate: function(user) {
            $rootScope.rootStatus = 'authenticated';
            $rootScope.rootUser = user;
            $rootScope.rootEmployee = {};
            $rootScope.rootClient = {};
            return apiRequest.get('employee', [user.uid], {
              expand: [
                {
                  resource: 'client'
                }
              ]
            }, function(response) {
              if (response.code === 200) {
                $rootScope.rootEmployee = response.response.data;
                return $rootScope.rootClient = $rootScope.rootEmployee.client;
              }
            });
          },
          unauthenticate: function() {
            return socket.emit('authenticate:unauthenticate', {}, function() {
              $rootScope.rootStatus = 'login';
              $rootScope.rootUser = {};
              $rootScope.rootEmployee = {};
              return $rootScope.rootClient = {};
            });
          }
        };
      }
    ]);
  });

}).call(this);
