// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'underscore', 'io'], function(app, _, io) {
    var apiVersion;
    apiVersion = 'v1';
    return app.factory('socket', [
      '$rootScope', function($rootScope) {
        var factory, socket;
        socket = io.connect();
        return factory = {
          on: function(eventName, callback) {
            return socket.on(eventName, function() {
              var args;
              args = arguments;
              return $rootScope.$apply(function() {
                return callback.apply(socket, args);
              });
            });
          },
          emit: function(eventName, data, callback) {
            return socket.emit(eventName, data, function() {
              var args;
              args = arguments;
              return $rootScope.$apply(function() {
                return callback.apply(socket, args);
              });
            });
          },
          apiRequest: function(method, url, query, data, callback) {
            url = '/' + apiVersion + url;
            return socket.emit('apiRequest', {
              method: method,
              url: url,
              data: data,
              query: query
            }, function(response) {
              var args;
              args = arguments;
              return $rootScope.$apply(function() {
                return callback.apply(socket, args);
              });
            });
          }
        };
      }
    ]);
  });

}).call(this);
