// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'angular'], function($, angular) {
    return function(Module) {
      Module.run(['$templateCache', function($templateCache) {}]);
      return Module.controller('ControllerWidgetExerciseScheduleCalendar', ['$scope', '$route', '$routeParams', 'apiRequest', function($scope, $route, $routeParams, apiRequest) {}]);
    };
  });

}).call(this);
