// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'text!views/widget4oh4/viewWidget4oh4.html'], function(angular, viewWidget4oh4) {
    return function(Module) {
      Module.run([
        '$templateCache', function($templateCache) {
          return $templateCache.put('viewWidget4oh4', viewWidget4oh4);
        }
      ]);
      return Module.controller('ControllerWidget4oh4', ['$scope', '$route', function($scope, $route) {}]);
    };
  });

}).call(this);
