// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'text!views/widgetActivityFeed/viewWidgetActivityFeed.html', 'text!views/widgetActivityFeed/partials/viewPartialActivityFeedCreateDictionary.html', 'text!views/widgetActivityFeed/partials/viewPartialActivityFeedCreateEmployee.html', 'text!views/widgetActivityFeed/partials/viewPartialActivityFeedCreateEvent.html', 'text!views/widgetActivityFeed/partials/viewPartialActivityFeedEventInitialized.html'], function(app, viewWidgetActivityFeed, viewPartialActivityFeedCreateDictionary, viewPartialActivityFeedCreateEmployee, viewPartialActivityFeedCreateEvent, viewPartialActivityFeedEventInitialized) {
    app.run([
      '$templateCache', function($templateCache) {
        $templateCache.put('viewWidgetActivityFeed', viewWidgetActivityFeed);
        $templateCache.put('viewPartialActivityFeedCreateDictionary', viewPartialActivityFeedCreateDictionary);
        $templateCache.put('viewPartialActivityFeedCreateEmployee', viewPartialActivityFeedCreateEmployee);
        $templateCache.put('viewPartialActivityFeedCreateEvent', viewPartialActivityFeedCreateEvent);
        return $templateCache.put('viewPartialActivityFeedEventInitialized', viewPartialActivityFeedEventInitialized);
      }
    ]);
    return app.controller('ControllerWidgetActivityFeed', [
      '$scope', '$templateCache', 'socket', 'apiRequest', function($scope, $templateCache, socket, apiRequest) {
        $scope.title = 'Themis';
        $scope.subtitle = 'by Cobar Systems LLC';
        return $scope.fetchActivity();
      }
    ]);
  });

}).call(this);
