// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore'], function(_) {
    return function($rootScope) {
      var helperSortHash;
      $rootScope.getKeysLength = function(obj) {
        var key, length, value;
        length = 0;
        for (key in obj) {
          value = obj[key];
          if (!_.isUndefined(value['uid']) && _.isNull(value['deletedAt'])) {
            length++;
          }
        }
        return length;
      };
      $rootScope.escapeHtml = function(str) {
        var div;
        div = document.createElement('div');
        div.appendChild(document.createTextNode(str));
        return div.innerHTML;
      };
      helperSortHash = function(hash, timeProp) {
        var hashArray, sortedHashArray;
        if (timeProp == null) {
          timeProp = 'createdAt';
        }
        hashArray = _.toArray(hash);
        return sortedHashArray = _.sortBy(hashArray, function(obj) {
          return new Date(obj[timeProp]);
        });
      };
      $rootScope.getLastObjectFromHash = function(hash, timeProp) {
        var sortedHashArray;
        if (timeProp == null) {
          timeProp = 'createdAt';
        }
        sortedHashArray = helperSortHash(hash, timeProp);
        return _.last(sortedHashArray);
      };
      $rootScope.getFirstObjectFromHash = function(hash, timeProp) {
        var sortedHashArray;
        if (timeProp == null) {
          timeProp = 'createdAt';
        }
        sortedHashArray = helperSortHash(hash, timeProp);
        return _.first(sortedHashArray);
      };
      return $rootScope.getArrayFromHash = function(hash) {
        var prop, resArray, val;
        resArray = [];
        for (prop in hash) {
          val = hash[prop];
          resArray.push(val);
        }
        return resArray;
      };
    };
  });

}).call(this);
