// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'soundmanager2'], function($, soundManager) {
    var sounds, windowHasFocus;
    windowHasFocus = true;
    $(window).bind('blur', function() {
      return windowHasFocus = false;
    });
    $(window).bind('focus', function() {
      return windowHasFocus = true;
    });
    sounds = {
      alert: {
        play: function() {}
      }
    };
    soundManager.url = window.location.protocol + '//' + window.location.host + '/assets/soundmanager2/soundmanager2.swf';
    soundManager.beginDelayedInit();
    soundManager.onready(function() {
      return sounds.alert = soundManager.createSound({
        id: 'alertSound',
        url: window.location.protocol + '//' + window.location.host + '/assets/gentleRoll.mp3',
        volume: '50',
        autoPlay: false
      });
    });
    return sounds;
  });

}).call(this);
