// Generated by CoffeeScript 1.6.3
(function() {
  define(['underscore'], function(_) {
    return function(object) {
      var cache, value;
      cache = [];
      value = JSON.stringify(object, function(key, value) {
        console.log('stacky');
        if (_.isObject(value)) {
          if (cache.indexOf(value) > -1) {
            return;
          }
          cache.push(value);
        }
        return value;
      });
      cache = null;
      return value;
    };
  });

}).call(this);
