// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery'], function(app, $) {
    return app.directive('animateRouteChange', [
      function() {
        return function(scope, element, attrs) {
          return scope.$on('$routeChangeSuccess', function(event, current, previous) {
            var hash, menuHash;
            hash = window.location.hash;
            menuHash = element.find('> a').attr('data-ng-href');
            if (hash.indexOf(menuHash) === 0) {
              if (element.find('.sub > li').length > 0 && !element.find('.sub').is(':visible')) {
                return element.find('.sub').hide().slideDown('fast');
              }
            } else {
              if (element.find('.sub > li').length > 0) {
                return element.find('.sub').slideUp('fast');
              }
            }
          });
        };
      }
    ]);
  });

}).call(this);
