// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui', 'underscore'], function(app, $, jqueryUi, _) {
    return app.directive('calendar', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          template: '<div class="calendar"></div>',
          scope: {
            options: '=options',
            activateWatch: '=activateWatch',
            refetchOnPost: '@refetchOnPost',
            refetchOnPut: '@refetchOnPut',
            updateOnChange: '=updateOnChange'
          },
          link: function($scope, element, attrs) {
            var activate, activated, calendarElem;
            calendarElem = element.find('.calendar');
            activated = false;
            activate = function() {
              if (activated) {
                return;
              }
              activated = true;
              return calendarElem.fullCalendar($scope.options);
            };
            $scope.$on('resourcePost', function(e, data) {
              if (data['resourceName'] === $scope.refetchOnPost) {
                return calendarElem.fullCalendar('refetchEvents');
              }
            });
            $scope.$on('resourcePut', function(e, data) {
              if (data['resourceName'] === $scope.refetchOnPut) {
                return calendarElem.fullCalendar('refetchEvents');
              }
            });
            $scope.$watch('updateOnChange', function() {
              calendarElem.fullCalendar('redrawEvents');
              return calendarElem.fullCalendar('refetchEvents');
            });
            return $scope.$watch('activateWatch', function() {
              if ($scope.activateWatch === true) {
                return activate();
              }
            }, true);
          }
        };
      }
    ]);
  });

}).call(this);
