// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui'], function(app, $, jqueryUi) {
    return app.directive('datepicker', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          scope: {
            months: '@months',
            model: '=model'
          },
          replace: true,
          link: function(scope, iterStartElement, attrs) {
            return iterStartElement.datepicker({
              dateFormat: 'yy-mm-dd',
              numberOfMonths: parseInt(scope.months || 1),
              onSelect: function(dateText, inst) {
                console.log(arguments);
                return scope.$apply(function(scope) {
                  scope.model = dateText;
                });
              }
            });
          }
        };
      }
    ]);
  });

}).call(this);
