// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'jquery-ui'], function(app, $, jqueryUi) {
    return app.directive('dateTimePicker', [
      function() {
        var directive;
        return directive = {
          restrict: 'A',
          scope: {
            model: '=model',
            form: '=form'
          },
          replace: true,
          link: function($scope, element, attrs) {
            return element.datetimepicker({
              showMeridian: true,
              startDate: new Date(),
              autoclose: true,
              minuteStep: 1,
              format: 'dd MM yyyy - HH:ii P'
            }).on('changeDate', function(e) {
              var d1, d2;
              d1 = new Date(e.date);
              d2 = new Date(d1.getTime() + (d1.getTimezoneOffset() * 60000));
              d2 = new Date(d2.setSeconds(0));
              return $scope.$apply(function() {
                $scope.model = d2;
                return $scope.form.$pristine = false;
              });
            });
          }
        };
      }
    ]);
  });

}).call(this);
