// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'underscore', 'underscore_string', 'spacetree'], function(app, $, _, underscore_string, $jit) {
    return app.directive("spaceTree", [
      '$compile', function($compile) {
        var directive;
        return directive = {
          restrict: 'A',
          scope: 'isolate',
          link: function(scope, element, attrs) {
            var id, json, st;
            json = {
              id: 'node02',
              name: 'Acme Corporation',
              data: {},
              children: [
                {
                  id: 'node03',
                  name: 'Accounting',
                  data: {},
                  children: [
                    {
                      id: 'nodea1',
                      name: 'brazin',
                      data: {},
                      children: []
                    }
                  ]
                }, {
                  id: 'node04',
                  name: 'Manufacturing Ops',
                  data: {},
                  children: [
                    {
                      id: 'nodea1',
                      name: 'brazin',
                      data: {},
                      children: []
                    }
                  ]
                }, {
                  id: 'node05',
                  name: 'Sales',
                  data: {},
                  children: []
                }
              ]
            };
            id = 'food';
            element.attr('id', id);
            st = new $jit.ST({
              injectInto: id,
              duration: 500,
              transition: $jit.Trans.Quart.easeInOut,
              levelDistance: 100,
              Navigation: {
                enable: true,
                panning: true
              },
              Node: {
                width: 200,
                autoHeight: true,
                type: 'rectangle',
                color: '#4b8df8',
                overridable: true
              },
              Edge: {
                type: 'bezier',
                overridable: true
              },
              onBeforeCompute: function(node) {
                console.log('---');
                return console.log(node.name);
              },
              onAfterCompute: function() {
                return console.log('done');
              },
              onCreateLabel: function(label, node) {
                console.log(node);
                console.log(label);
                label.id = node.id;
                label.innerHTML = node.name;
                label.style.width = '200px';
                label.style.color = '#FFF';
                label.style.fontSize = '12px';
                return label.style.textAlign = 'center';
              },
              onBeforePlotNode: function(node) {},
              onBeforePlotLine: function(adj) {}
            });
            st.loadJSON(json);
            st.compute();
            return st.onClick(st.root);
          }
        };
      }
    ]);
  });

}).call(this);
