// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery'], function(app, $) {
    return app.directive('animateIn', [
      function() {
        return function(scope, element, attrs) {
          var $el, loadingHTML, num, timer;
          element.addClass('animated fadeIn');
          loadingHTML = "<div class=\"loading-indicator\">          <div class=\"progress progress-striped active\">            <div style=\"width: 100%;\" class=\"bar\"></div>          </div>        </div>";
          num = 0;
          $el = element;
          $el.removeClass('widget-themis-finish');
          $el.addClass('widget-themis');
          $el.css('position', 'relative');
          return timer = setInterval(function() {
            var init_opacity, max;
            max = 4;
            num = num + 1;
            $el = element;
            init_opacity = 1;
            if (num > max) {
              clearTimeout(timer);
              $el.removeClass('widget-themis');
              $el.addClass('widget-themis-finish');
              $el.css('position', '');
              return;
            }
            return $el.css({
              'border-right': '0px !important',
              'box-shadow': num + 'px ' + num + 'px 0 0 rgba(0,0,0,0.35)',
              top: (4 - num) + 'px',
              left: (4 - num) + 'px'
            });
          }, 50);
        };
      }
    ]);
  });

}).call(this);
