// Generated by CoffeeScript 1.6.3
(function() {
  define(['app'], function(app) {
    return app.controller('ControllerWidgetExerciseBuilderFieldManageSlider', [
      '$scope', 'apiRequest', '$dialog', function($scope, apiRequest, $dialog) {
        return $scope.slider = {
          value: 50,
          step: 5
        };
      }
    ]);
  });

}).call(this);
