// Generated by CoffeeScript 1.6.3
(function() {
  define(['app'], function(app) {
    return app.controller('ControllerWidgetExerciseBuilderFieldManageOpenResponse', ['$scope', 'apiRequest', '$dialog', function($scope, apiRequest, $dialog) {}]);
  });

}).call(this);
