// Generated by CoffeeScript 1.6.3
(function() {
  define(['text!views/widgetTabs/viewWidgetTabs.html'], function(viewWidgetTabs) {
    return function(Module) {
      Module.run([
        '$templateCache', function($templateCache) {
          return $templateCache.put('viewWidgetTabs', viewWidgetTabs);
        }
      ]);
      return Module.controller('ControllerWidgetTabs', [
        '$scope', '$rootScope', 'socket', 'apiRequest', function($scope, $rootScope, socket, apiRequest) {
          var viewModel, widget, _i, _len, _ref;
          _ref = $scope.widgetsData['viewWidgetTabs'].tabs;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            widget = _ref[_i];
            $rootScope.widgetsData[widget.widgetName] = widget.data;
          }
          viewModel = {};
          $scope.viewModel = viewModel;
          return viewModel.data = $rootScope.widgetsData['viewWidgetTabs'];
        }
      ]);
    };
  });

}).call(this);
