// Generated by CoffeeScript 1.6.3
(function() {
  define(['app'], function(app) {
    return app.controller('ControllerWidgetExerciseBuilderGroupFieldOpenResponse', [
      '$scope', 'apiRequest', '$dialog', function($scope, apiRequest, $dialog) {
        $scope.form = {};
        $scope.cancelAddNewField = function() {
          $scope.form = {};
          $scope.formOpenResponseAdd.$setPristine();
          return $scope.$parent.viewModel.cancelAddNewField();
        };
        $scope.submitField = function() {
          return apiRequest.post('field', {
            name: $scope.form.name,
            type: 'openResponse',
            groupUid: $scope.group.uid,
            ordinal: 0,
            openResponseMaxLength: $scope.form.maxLength,
            openResponseMinLength: $scope.form.minLength
          }, {}, function(response) {
            console.log(response);
            apiRequest.get('group', [$scope.group.uid], {
              expand: [
                {
                  resource: 'fields'
                }
              ]
            }, function(response) {
              console.log('updated group');
              return console.log(response);
            });
            return $scope.cancelAddNewField();
          });
        };
        return $scope.isFormInvalid = function() {
          if (!$scope.formOpenResponseAdd) {
            return;
          }
          return $scope.formOpenResponseAdd.$invalid;
        };
      }
    ]);
  });

}).call(this);
