// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var config;
    return config = {
      isRouteQuiz: function(path) {
        return path === '/quiz/:uid';
      },
      routes: {
        '/quiz/:uid': {
          title: 'quiz',
          root: '/quiz/:uid',
          subRoutes: [],
          widgets: ['viewWidgetQuiz']
        },
        '/profile': {
          title: 'Profile',
          root: '/profile',
          widgets: [],
          subRoutes: []
        },
        '/admin/themis': {
          title: 'Dashboard',
          root: '/admin/themis',
          subRoutes: [],
          widgets: ['viewWidgetActivityFeed']
        },
        '/admin/themis/templates': {
          title: 'Templates',
          root: '/admin/themis/templates',
          subRoutes: [],
          widgets: []
        },
        '/admin/themis/templates/exercises': {
          title: 'Templates - Exercises',
          root: '/admin/themis/templates/exercises',
          subRoutes: [
            {
              '/:templateUid/:revisionUid': {
                title: 'Templates',
                subMenuItem: false
              }
            }
          ],
          widgets: ['viewWidgetExerciseBuilder']
        },
        '/admin/themis/templates/quizes': {
          title: 'Templates - Quizes',
          root: '/admin/themis/templates/quizes',
          subRoutes: [
            {
              '/:templateUid/:revisionUid': {
                title: 'Templates',
                subMenuItem: false
              }
            }
          ],
          widgets: ['viewWidgetExerciseBuilder']
        },
        '/admin/themis/schedule': {
          title: 'Schedule',
          root: '/admin/themis/schedule',
          subRoutes: [
            {
              '/:eventUid': {
                title: 'Schedule',
                subMenuItem: false
              }
            }
          ],
          widgets: ['viewWidgetScheduler']
        },
        '/admin/themis/settings': {
          title: 'Dictionaries',
          root: '/admin/themis/settings',
          subRoutes: [],
          widgets: []
        },
        '/admin/themis/settings/dictionaries': {
          title: 'Dictionaries',
          root: '/admin/themis/settings/dictionaries',
          subRoutes: [
            {
              '/:dictionaryUid': {
                title: 'Dictionaries',
                subMenuItem: true
              }
            }
          ],
          widgets: ['viewWidgetDictionaryManager']
        },
        '/admin/themis/settings/employees': {
          title: 'Employees',
          root: '/delegate/themis/settings/employees',
          subRoutes: [
            {
              '/:employeeUid': {
                title: 'Employees',
                subMenuItem: false
              }
            }
          ],
          widgets: ['viewWidgetEmployeeManager']
        },
        '/admin/themis/exercises': {
          title: 'Exercises',
          root: '/admin/themis/exercises',
          subRoutes: [
            {
              '/:exerciseUid': {
                title: 'Exercises',
                subMenuItem: false
              }
            }
          ],
          widgets: ['viewWidgetFullExerciseSubmitter']
        },
        '/delegate/themis': {
          title: 'Dashboard',
          root: '/delegate/themis',
          subRoutes: [],
          widgets: []
        },
        '/delegate/themis/exercises': {
          title: 'Exercises',
          root: '/delegate/themis/exercises',
          subRoutes: [
            {
              '/:exerciseUid': {
                title: 'Exercises',
                subMenuItem: false
              }
            }
          ],
          widgets: []
        }
      },
      simplifiedUserCategories: {
        'clientSuperAdmin': 'admin',
        'clientAdmin': 'admin',
        'clientDelegate': 'delegate'
      },
      routeMatchClientType: function(route, clientType) {
        return route.indexOf('/' + this.simplifiedUserCategories[clientType]) === 0;
      }
    };
  });

}).call(this);
