// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'highcharts', 'text!views/widgetQuarterlyTestingReport/viewWidgetQuarterlyTestingReport.html'], function($, highcharts, viewWidgetQuarterlyTestingReport) {
    return function(Module) {
      Module.run([
        '$templateCache', function($templateCache) {
          return $templateCache.put('viewWidgetQuarterlyTestingReport', viewWidgetQuarterlyTestingReport);
        }
      ]);
      return Module.controller('ControllerWidgetQuarterlyTestingReport', [
        '$scope', '$templateCache', 'socket', 'apiRequest', function($scope, $templateCache, socket, apiRequest) {
          var viewModel;
          viewModel = {};
          $scope.viewModel = viewModel;
          return $('#highchart').highcharts({
            chart: {
              type: 'bar'
            },
            title: {
              text: 'Historic World Population by Region'
            },
            subtitle: {
              text: 'Source: Wikipedia.org'
            },
            xAxis: {
              categories: ['Africa', 'America', 'Asia', 'Europe', 'Oceania'],
              title: {
                text: null
              }
            },
            yAxis: {
              min: 0,
              title: {
                text: 'Population (millions)',
                align: 'high'
              },
              labels: {
                overflow: 'justify'
              }
            },
            tooltip: {
              valueSuffix: ' millions'
            },
            plotOptions: {
              bar: {
                dataLabels: {
                  enabled: true
                }
              }
            },
            legend: {
              layout: 'vertical',
              align: 'right',
              verticalAlign: 'top',
              x: -100,
              y: 100,
              floating: true,
              borderWidth: 1,
              backgroundColor: '#FFFFFF',
              shadow: true
            },
            credits: {
              enabled: false
            },
            series: [
              {
                name: 'Year 1800',
                data: [107, 31, 635, 203, 2]
              }, {
                name: 'Year 1900',
                data: [133, 156, 947, 408, 6]
              }, {
                name: 'Year 2008',
                data: [973, 914, 4054, 732, 34]
              }
            ]
          });
        }
      ]);
    };
  });

}).call(this);
