// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'underscore'], function(app, _) {
    return app.filter('tel', [
      function() {
        return function(tel) {
          var city, country, number, value;
          value = tel.toString().trim().replace(/^\+/, '');
          if (value.match(/[^0-9]/)) {
            return tel;
          }
          switch (value.length) {
            case 10:
              country = 1;
              city = value.slice(0, 3);
              number = value.slice(3);
              break;
            case 11:
              country = value[0];
              city = value.slice(3, 5);
              number = value.slice(4);
              break;
            case 12:
              country = value.slice(0, 3);
              city = value.slice(3, 5);
              number = value.slice(5);
              break;
            default:
              return tel;
          }
          if (country === 1) {
            country = '';
          }
          number = number.slice(0, 3) + '-' + number.slice(3);
          return (country + ' (' + city + ') ' + number).trim();
        };
      }
    ]);
  });

}).call(this);
