// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'underscore'], function(app, _) {
    return app.filter('deleted', [
      function() {
        return function(arr) {
          return _.filter(arr, function(item) {
            return !item.deletedAt;
          });
        };
      }
    ]);
  });

}).call(this);
