// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'angular', 'text!views/viewWidgetCoreFooter.html'], function(app, angular, viewWidgetCoreFooter) {
    app.run([
      '$templateCache', function($templateCache) {
        return $templateCache.put('viewWidgetCoreFooter', viewWidgetCoreFooter);
      }
    ]);
    return app.controller('ControllerWidgetCoreFooter', [
      '$scope', 'authenticate', function($scope, authenticate) {
        return $scope.logout = function() {
          return authenticate.unauthenticate();
        };
      }
    ]);
  });

}).call(this);
