// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'jquery', 'underscore', 'config/clientConfig', 'config/clientConfigHelperMethods', 'text!views/viewCore.html', 'text!config/clientOrmShare.json'], function(app, $, _, clientConfig, clientConfigHelperMethods, viewCore, clientOrmShare) {
    clientOrmShare = JSON.parse(clientOrmShare);
    app.run([
      '$templateCache', function($templateCache) {
        return $templateCache.put('viewCore', viewCore);
      }
    ]);
    return app.controller('ControllerApp', [
      '$rootScope', '$route', '$routeParams', 'socket', 'authenticate', function($rootScope, $route, $routeParams, socket, authenticate) {
        clientConfigHelperMethods($rootScope);
        $rootScope.clientConfig = clientConfig;
        $rootScope.clientOrmShare = clientOrmShare;
        $rootScope.rootStatus = 'food';
        $('body').removeClass('login');
        $('body').css('background-color', '#444').animate({
          'background-color': '#F1F1F1'
        }, 'slow');
        $rootScope.rootStatus = 'loading';
        $rootScope.loadingStatus = 'Connecting...';
        $rootScope.loadingStatusColor = '#35aa47 !important';
        $rootScope.loadingStatusIcon = 'icon-lock';
        $rootScope.routeParams = $routeParams;
        $rootScope.$on('$routeChangeSuccess', function(event, current, previous) {
          return $rootScope.routeParams = $routeParams;
        });
        return socket.emit('authenticate:status', {}, function(response) {
          if (response.authenticated && response.user) {
            return authenticate.authenticate(response.user);
          } else {
            return authenticate.unauthenticate();
          }
        });
      }
    ]);
  });

}).call(this);
