// Generated by CoffeeScript 1.6.3
(function() {
  define(['app', 'text!views/viewWidgetCoreLogin.html'], function(app, viewWidgetCoreLogin) {
    app.run([
      '$templateCache', function($templateCache) {
        return $templateCache.put('viewWidgetCoreLogin', viewWidgetCoreLogin);
      }
    ]);
    return app.controller('ControllerWidgetCoreLogin', [
      '$scope', '$templateCache', 'socket', 'authenticate', function($scope, $templateCache, socket, authenticate) {
        $scope.errorMessage = '';
        $scope.submitting = false;
        $scope.username = '';
        $scope.password = '';
        return $scope.authenticate = function() {
          $scope.errorMessage = '';
          if (!$scope.username || !$scope.password) {
            return $scope.errorMessage = 'Input your email and password';
          } else {
            $scope.submitting = true;
            return socket.emit('authenticate:authenticate', {
              username: $scope.username,
              password: $scope.password
            }, function(response) {
              $scope.submitting = false;
              if (response.success && response.user) {
                return authenticate.authenticate(response.user);
              } else {
                return $scope.errorMessage = 'Incorrect username or password';
              }
            });
          }
        };
      }
    ]);
  });

}).call(this);
